# src/config/__init__.py

from .settings import Settings, settings
from .constants import (
    DEFAULT_LLM_MODEL,
    DEFAULT_OCR_MODEL,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_RERANK_MODEL,
    DEFAULT_SQLITE_PATH,
    DEFAULT_QDRANT_PATH,
    DEFAULT_PDF_DIRECTORY,
    DEFAULT_COLLECTION_NAME,
    DEFAULT_RERANK_TOP_K,
    DEFAULT_FINAL_TOP_K,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_LANGUAGE,
    DEFAULT_QA_LANGUAGE,
    DEFAULT_MAX_ANSWER_LENGTH,
    DEFAULT_LOG_LEVEL,
)

__all__ = [
    "Settings",
    "settings",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_OCR_MODEL",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_RERANK_MODEL",
    "DEFAULT_SQLITE_PATH",
    "DEFAULT_QDRANT_PATH",
    "DEFAULT_PDF_DIRECTORY",
    "DEFAULT_COLLECTION_NAME",
    "DEFAULT_RERANK_TOP_K",
    "DEFAULT_FINAL_TOP_K",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_LANGUAGE",
    "DEFAULT_QA_LANGUAGE",
    "DEFAULT_MAX_ANSWER_LENGTH",
    "DEFAULT_LOG_LEVEL",
]
